### ISSUE TITLE
Domain model Question

### ISSUE THREAD

**Issue by boskiv** [Creatly/creatly-backend#123]
https://github.com/Creatly/creatly-backend/blob/2f0ca56eddd77fcf32f8d2c78f38115bee2a1009/internal/domain/student.go#L13

@zhashkevych 

Пытаюсь реализовать похожую структуру у себя в проекте

Скажи плиз в этом есть какой то сакральный смысл чтобы хранить пользователей разных типов по разным моделям? Использование ролей как то ломает бизнес логику или усложняет реализацию?

**Comment by zhashkevych** [comment]
@boskiv Привет! 
Разделение учеников и админов на разные структуры/таблицы сделано для упрощения бизнес-логики, поскольку  ученики и админы имеют доступ к разным "подприложениям" (кабинету студента и админки соответственно).

На уровне админки уже пользователь "Админ" может в будущем иметь разграничение прав по ролям

**Comment by zhashkevych** [comment]
@boskiv извини что ответил с задержкой, не заметил вопрос среди всех оповещений
